fix: naming

diff --git a/.github/workflows/deploy-blue-green.yml b/.github/workflows/deploy-blue-green.yml
--- a/.github/workflows/deploy-blue-green.yml
+++ b/.github/workflows/deploy-blue-green.yml
@@ -73,12 +73,12 @@ jobs:
                   # Write the contents of TERRAFORM_VARS to tfvars.json.
                   cat <<< "$TERRAFORM_VARS" > tfvars.json
                   # Store the active environment in a variable
-                  active_env="$(terraform output -raw active_environment)"
-                  echo "Active environment is: $active_env"
-                  if [ "$active_env" == "${{ github.event.inputs.deploy_instance }}" ]; then
-                      echo "Error: Active environment is the same as the deploy environment." >&2
+                  active_deployment="$(terraform output -raw active_deployment)"
+                  echo "Active deployment is: $active_deployment"
+                  if [ "$active_deployment" == "${{ github.event.inputs.deploy_instance }}" ]; then
+                      echo "Error: Active deployment is the same as the deploy environment." >&2
                       exit 1
                   fi
-                  terraform apply -var-file=tfvars.json -auto-approve -var="DEPLOYMENT_STATE=deploying" -var="ACTIVE_ENVIRONMENT=${active_env}"
+                  terraform apply -var-file=tfvars.json -auto-approve -var="DEPLOYMENT_STATE=deploying" -var="ACTIVE_DEPLOYMENT=${active_deployment}"
               env:
                   TERRAFORM_VARS: ${{ vars.TERRAFORM_VARS }}
diff --git a/.github/workflows/destroy-blue-green.yml b/.github/workflows/destroy-blue-green.yml
--- a/.github/workflows/destroy-blue-green.yml
+++ b/.github/workflows/destroy-blue-green.yml
@@ -71,11 +71,11 @@ jobs:
                   fi
                   # Write the contents of TERRAFORM_VARS to tfvars.json.
                   cat <<< "$TERRAFORM_VARS" > tfvars.json
-                  active_env=$(terraform output -raw active_environment)
-                  if [ "$active_env" == "${{ github.event.inputs.destroy_instance }}" ]; then
-                      echo "Error: Active environment is the same as the destroy instance." >&2
+                  active_deployment=$(terraform output -raw active_deployment)
+                  if [ "$active_deployment" == "${{ github.event.inputs.destroy_instance }}" ]; then
+                      echo "Error: Active deployment is the same as the destroy instance." >&2
                       exit 1
                   fi
-                  terraform apply -var-file=tfvars.json -auto-approve -var="DEPLOYMENT_STATE=single" -var="ACTIVE_ENVIRONMENT=$active_env"
+                  terraform apply -var-file=tfvars.json -auto-approve -var="DEPLOYMENT_STATE=single" -var="ACTIVE_DEPLOYMENT=$active_deployment"
               env:
                   TERRAFORM_VARS: ${{ vars.TERRAFORM_VARS }}
diff --git a/.github/workflows/promote-blue-green.yml b/.github/workflows/promote-blue-green.yml
--- a/.github/workflows/promote-blue-green.yml
+++ b/.github/workflows/promote-blue-green.yml
@@ -71,10 +71,10 @@ jobs:
                   fi
                   # Write the contents of TERRAFORM_VARS to tfvars.json.
                   cat <<< "$TERRAFORM_VARS" > tfvars.json
-                  if [ "$(terraform output -raw active_environment)" == "${{ github.event.inputs.promote_instance }}" ]; then
-                      echo "Error: Active environment is the same as the promote instance." >&2
+                  if [ "$(terraform output -raw active_deployment)" == "${{ github.event.inputs.promote_instance }}" ]; then
+                      echo "Error: Active deployment is the same as the promote instance." >&2
                       exit 1
                   fi
-                  terraform apply -var-file=tfvars.json -auto-approve -var="DEPLOYMENT_STATE=deploying" -var="ACTIVE_ENVIRONMENT=${{ github.event.inputs.promote_instance }}"
+                  terraform apply -var-file=tfvars.json -auto-approve -var="DEPLOYMENT_STATE=deploying" -var="ACTIVE_DEPLOYMENT=${{ github.event.inputs.promote_instance }}"
               env:
                   TERRAFORM_VARS: ${{ vars.TERRAFORM_VARS }}
